name: Auto Merge OpenAPI Spec

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  validate-and-merge:
    if: github.actor == 'obeth-m-19991'  # Replace with your bot's username
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        
      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            if (pr.data.user.login === 'obeth-m-19991') {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash',
              });
              console.log("PR merged successfully.");
            } else {
              console.log("PR not from CI bot, skipping merge.");
            }
